version: "3.9"

services:
  shop:
    build: ./shop
    container_name: shop
    ports:
      - "8000:8000"
    volumes:
      - ./shop/app:/app/app
    environment:
      PYTHONUNBUFFERED: 1
    restart: unless-stopped
    networks:
      - shop_network

  email-service:
    build: ./email
    container_name: email-service
    ports:
      - "5001:5001"
    networks:
      - shop_network

  push-service:
    build: ./push
    container_name: push-service
    ports:
      - "5002:5002"
    networks:
      - shop_network

  payment-service:
    build: ./payment
    container_name: payment-service
    ports:
      - "5003:5003"
    networks:
      - shop_network

  shipping-service:
    build: ./shipping
    container_name: shipping-service
    ports:
      - "5004:5004"
    networks:
      - shop_network

  order-service:
    build: ./order
    container_name: order-service
    ports:
      - "5005:5005"
    networks:
      - shop_network


networks:
  shop_network:
    name: shop_network