include:
  - ./shop/docker-compose.yml
  - ./email/docker-compose.yml
  - ./push/docker-compose.yml
  - ./payment/docker-compose.yml
  - ./shipping/docker-compose.yml
  - ./order/docker-compose.yml
  - ./search/docker-compose.yml

services:
  rabbitmq:
    image: "rabbitmq:management"  # используем образ с включенным управлением
    hostname: rabbitmqhost
    restart: always
    ports:
      - "5672:5672"  # порт для AMQP
      - "15672:15672"  # порт для управляющего интерфейса
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq  # сохраняем данные на диске
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmqlogin  # имя пользователя
      - RABBITMQ_DEFAULT_PASS=rabbitmqpassword  # пароль
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 1431655766  # 1.3 Gib
    networks:
      - shop_network

volumes:
  rabbitmq_data:

networks:
  shop_network:
    name: shop_network