version: "3.9"

services:
  email-service:
    build: ./email
    container_name: email-service
    ports:
      - "5001:5001"
    networks:
      - shop_network

  push-service:
    build: ./push
    container_name: push-service
    ports:
      - "5002:5002"
    environment:
      VAPID_PUBLIC_KEY: "тут ключ"
      VAPID_PRIVATE_KEY: "тут ключ"
    networks:
      - shop_network

  shop:
    build: ./shop
    container_name: shop
    ports:
      - "8000:8000"
    volumes:
      - ./shop/app:/app/app
    environment:
      PYTHONUNBUFFERED: 1
    restart: unless-stopped
    networks:
      - shop_network


networks:
  shop_network:
    name: shop_network