include:
  - ./shop/docker-compose.yml
  - ./email/docker-compose.yml
  - ./push/docker-compose.yml
  - ./payment/docker-compose.yml
  - ./shipping/docker-compose.yml
  - ./order/docker-compose.yml
  - ./search/docker-compose.yml

networks:
  shop_network:
    name: shop_network