services:
  shard1:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - shard1_data:/var/lib/postgresql/data
    networks:
      - shop_network

  shard2:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - shard2_data:/var/lib/postgresql/data
    networks:
      - shop_network

  shard3:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - shard3_data:/var/lib/postgresql/data
    networks:
      - shop_network

  search-service:
    build: ./
    container_name: search-service
    ports:
      - "5006:5006"
    environment:
      # os.getenv("SHARD1_DATABASE_URL") !!! Изучить переменные окружения
      # эти URL используются в app/db.py по умолчанию; override если нужно
      SHARD1_DATABASE_URL: "postgresql://postgres:postgres@shard1:5432/postgres"
      SHARD2_DATABASE_URL: "postgresql://postgres:postgres@shard2:5432/postgres"
      SHARD3_DATABASE_URL: "postgresql://postgres:postgres@shard3:5432/postgres"
    depends_on:
      - shard1
      - shard2
      - shard3
    networks:
      - shop_network

volumes:
  shard1_data:
  shard2_data:
  shard3_data:

networks:
  shop_network:
    name: shop_network