services:
  redis:
    image: redis:7.4-alpine
    container_name: search-cache
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "default"]
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: redis
      REDIS_PASSWORD: default
      REDIS_USERNAME: default
      REDIS_DATABASE: 1
    volumes:
      - redis_data:/app/data
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "default", "PING"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - shop_network

  search-cache-service:
    build: ./
    container_name: search-cache-service
    ports:
      - "5007:5007"
    depends_on:
      - redis
    networks:
      - shop_network

volumes:
  redis_data:

networks:
  shop_network:
    name: shop_network